name: test
on: [push]
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          coverage: none

      - id: set-matrix
        run: php tools/matrix.php
  run:
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    name: PHP ${{ matrix.php }} Test on ${{ matrix.os }}
    env:
      shouldBuild: ${{ matrix.shouldBuild && matrix.os == 'ubuntu-latest' && matrix.php == '8.0' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, sockets
          coverage: none

      - name: Check environment
        run: |
          php --version
          composer --version

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ matrix.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ matrix.os }}-composer-${{ matrix.php }}-

      - name: Install dependencies
        run: |
          composer install --prefer-dist

      - name: Run tests
        run: |
          php vendor/bin/phpunit

      - name: Convert phabel
        if: ${{ env.shouldBuild }}
        run: |
          php tools/configGit.php
          php tools/convertPhabel.php all

      - name: Convert phabel (dry run)
        if: ${{ !env.shouldBuild }}
        run: |
          php tools/convertPhabel.php all dry