name: test
on: [push]
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          coverage: none

      - id: set-matrix
        run: php tools/ci/matrix.php
  run:
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    name: PHP ${{ matrix.php }} Test on ${{ matrix.os }}
    env:
      shouldBuild: ${{ matrix.shouldBuild == 'yes' && matrix.os == 'ubuntu-latest' && matrix.php == '8.0' }}
      shouldTag: ${{ matrix.shouldTag }}
      PHP_CS_FIXER_IGNORE_ENV: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring, intl, sockets
          coverage: none

      - name: Check environment
        run: |
          php --version
          composer --version

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ matrix.os }}-phabel-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ matrix.os }}-phabel-${{ matrix.php }}-

      - name: Install dependencies
        env:
          PHABEL_TARGET: ${{ matrix.php }}
        run: |
          bash -x tools/ci/prepareDeps.sh

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, sockets
          coverage: none

      - name: Run tests
        run: |
          php vendor/bin/phpunit

      - name: Convert phabel
        if: ${{ env.shouldBuild == 'true' }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "Github Actions"
          php tools/convertPhabel.php all

      - name: Convert phabel (dry run)
        if: ${{ env.shouldBuild == 'false' }}
        run: |
          php tools/convertPhabel.php all dry
