name: coverage
on: 
  push:
    paths:
    - '**.php'
  pull_request:
    paths:
    - '**.php'
jobs:
  run:
    runs-on: ubuntu-latest
    name: Coverage tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          extensions: mbstring, intl, sockets
          coverage: pcov

      - name: Check environment
        run: |
          php --version
          composer --version
          
      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ matrix.os }}-phabel-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ matrix.os }}-phabel-${{ matrix.php }}-

      - name: Install dependencies
        run: |
          bash -x tools/ci/prepareDeps.sh

      - name: Run tests
        env:
          PHABEL_COVERAGE: coverage/convertPhabel
        run: |
          php vendor/bin/phpunit --coverage-php=coverage/phpunit.php
          php tools/convertPhabel.php all dry
          php tools/testExprGen.php

      - name: Merge coverage
        run: |
          composer coverage

      - name: Upload coverage to Codecov
        env: 
          OS: ${{ matrix.os }}
          PHP: "8.0"
        uses: codecov/codecov-action@v1
        with:
           file: coverage/clover.xml
           env_vars: OS,PHP
