name: build
on:
  pull_request:
  push:
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        php-versions: ["7.4", "8.0"]
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, sockets
          coverage: none

      - name: Check environment
        run: |
          php --version
          composer --version

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ matrix.os }}-composer-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ matrix.os }}-composer-${{ matrix.php-versions }}-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run tests
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1
        run: |
          phpdbg -qrr vendor/bin/phpunit --coverage-php=coverage/phpunit.php
          phpdbg -qrr tools/testExprGen.php
          composer coverage

      - name: Upload coverage to Codecov
        env: 
          OS: ${{ matrix.os }}
          PHP: ${{ matrix.php-versions }}
        uses: codecov/codecov-action@v1
        with:
           file: coverage/clover.xml
           env_vars: OS,PHP
